import React from 'react'
import classnames from 'classnames'
import Layout from '@theme/Layout'
import Link from '@docusaurus/Link'
import useDocusaurusContext from '@docusaurus/useDocusaurusContext'
import useBaseUrl from '@docusaurus/useBaseUrl'
import styles from './styles.module.css'
import { Container, Row} from 'react-bootstrap'
import vidStyles from './video.css'


function BussVid1() {
    const context = useDocusaurusContext()
    const { siteConfig = {} } = context
    return (
        <Layout title="Business" description={siteConfig.tagline}>
            <main className="ArchivePage" >
                {/* HEADER */}
                <header className={classnames('hero full', styles.heroBanner)}>
                    {/* HOW */}
                    <section className={styles.forTopics}>
                        <div className="container" color="blue">
                            <div className={classnames('row', styles.responsiveCentered)}>
                                <div className="col col--6 col--offset-3">
                                    <h2 className="">Bussiness Sessions</h2>
                                    <p className="">Are you more of a visual learner, then look no further. Find the topic of your interest below and and enjoy the turorial </p>
                                </div>
                            </div>

                            <Row>
                                <Container>
                                    <div className="App">

                                        <h2>Entrepreneur</h2>
                                        <div className={vidStyles.videoContainer} 
                                            style={{alignItems: 'center',
                                            display: 'inline',
                                            float: 'left',
                                            border: '1px solid black',
                                            margin: '5px 10px 10px 0px',}} 
                                            >
                                            <iframe width="560" height="315" src='https://www.youtube.com/embed/7bMpgBuoZY0'
                                                frameBorder='0'
                                                allow='autoplay; encrypted-media; accelerometer; gyroscope; picture-in-picture'
                                                allowFullScreen
                                            />
                                        </div>
                                        <h6>What is an Entrepreneur?</h6>
                                        <p className="description">
                                            An entrepreneur is someone who organizes, manages, and assumes the risks of a business or enterprise. 
                                            An entrepreneur is an agent of change. Entrepreneurship is the process of discovering new ways of combining resources. 
                                            When the market value generated by this new combination of resources is greater than the market value these resources 
                                            can generate elsewhere individually or in some other combination, the entrepreneur makes a profit. An entrepreneur who 
                                            takes the resources necessary to produce a pair of jeans that can be sold for thirty dollars and instead turns them into 
                                            a denim backpack that sells for fifty dollars will earn a profit by increasing the value those resources create
                                        </p>                                     
                                    </div>
                                </Container>
                            </Row>

                            <Row>
                                <Container>
                                    <div className="App">

                                        <h2>Marketing</h2>
                                        <div className={vidStyles.videoContainer} 
                                            style={{alignItems: 'center',
                                            display: 'inline',
                                            float: 'left',
                                            border: '1px solid black',
                                            margin: '5px 10px 10px 0px',}} >
                                            <iframe width="560" height="315" src='https://www.youtube.com/embed/A2t-yhFaUC0'
                                                frameBorder='0'
                                                allow='autoplay; encrypted-media; accelerometer; gyroscope; picture-in-picture'
                                                allowFullScreen
                                                title='video'
                                            />
                                        </div>   
                                        <h6>What is Marketing?</h6>
                                        <p className="description">
                                            marketing refers to the activities of a company associated with buying and selling a product or service. 
                                            It includes advertising, selling and delivering products to people. people who work in marketing departments 
                                            of companies try to get the attention of target audiences by using slogans, packaging design, celebrity endorsements 
                                            and general media exposure
                                        </p>                                      
                                    </div>
                                </Container>
                            </Row>

                            <Row>
                                <Container>
                                    <div className="App">

                                        <h2>Strategic Planning</h2>
                                        <div className={vidStyles.videoContainer} 
                                            style={{alignItems: 'center',
                                            display: 'inline',
                                            float: 'left',
                                            border: '1px solid black',
                                            margin: '5px 10px 10px 0px',}} >
                                            <iframe width="560" height="315" src='https://www.youtube.com/embed/o0UXAhzTkHE'
                                                frameBorder='0'
                                                allow='autoplay; encrypted-media; accelerometer; gyroscope; picture-in-picture'
                                                allowFullScreen
                                                title='video'
                                            />
                                        </div>
                                        <h6>What is Strategic Planning?</h6>
                                        <p className="description">
                                            Strategic planning is the process of documenting and establishing a direction of your small business—by assessing both 
                                            where you are and where you’re going. The strategic plan gives you a place to record your mission, vision, and values, 
                                            as well as your long-term goals and the action plans you’ll use to reach them. A well-written strategic plan can play a 
                                            pivotal role in your small business’s growth and success because it tells you and your employees how best to respond to 
                                            opportunities and challenges.
                                        </p>  
                                    </div>
                                </Container>
                            </Row>

                            <Row>
                                <Container>
                                    <div className="App">

                                        <h2>Accounting and Finance</h2>
                                        <div className={vidStyles.videoContainer} 
                                            style={{alignItems: 'center',
                                            display: 'inline',
                                            float: 'left',
                                            border: '1px solid black',
                                            margin: '5px 10px 10px 0px',}} >
                                            <iframe width="560" height="315" src='https://www.youtube.com/embed/YjkRSlTxsZM'
                                                frameBorder='0'
                                                allow='autoplay; encrypted-media; accelerometer; gyroscope; picture-in-picture'
                                                allowFullScreen
                                                title='video'
                                            />
                                        </div>
                                        <h6>What is Accounting and Finance?</h6>
                                        <p className="description">
                                            learn about external financial statements, internal managerial accounting reports, income tax systems 
                                            and how they interact in business decision-making. in this course, we review the accounting equation, 
                                            the three primary financial statements, how to use accounting basics to aid decision making, and how income 
                                            taxes figure into business and personal decisions.
        
                                        </p>               
                                    </div>
                                </Container>
                            </Row>

                            <Row>
                                <Container>
                                    <div className="App">
                                        
                                        <h2>Business Technology</h2>
                                        <div className={vidStyles.videoContainer} 
                                            style={{alignItems: 'center',
                                            display: 'inline',
                                            float: 'left',
                                            border: '1px solid black',
                                            margin: '5px 10px 10px 0px',}} >
                                            <iframe width="560" height="315" src='https://www.youtube.com/embed/ODS_jCocCwg'
                                                frameBorder='0'
                                                allow='autoplay; encrypted-media; accelerometer; gyroscope; picture-in-picture'
                                                allowFullScreen
                                                title='video'
                                            />
                                        </div>
                                        <h6>What is Business Technology?</h6>
                                        <p className="description">
                                            TO DO
                                        </p>
                                    </div>
                                </Container>
                            </Row>   
                        </div>
                    </section>
                </header>
            </main>
            <Link
                className={classnames(
                    'button hero--button button--md button--secondary button--outline responsive-button',
                    styles.button
                )}
                to={useBaseUrl('/bussVid2')}
                style={{ marginLeft: 200, marginTop: 10, float: "center" }}
                >
                Next
            </Link>
        </Layout >
    )
}

export default BussVid1